Build: discord v13 support, slashcommands support.
commclassroom/classroom-monitor-bot pull request #146
Opened 2021-12-29 09:01 UTC by DhansAL

# Description

This pull request resolves issues #143  #102
 - Added support to discord `v13.4.0`.
 - Restructured code, created specific event handlers,modules,etc.
 - Added support for slashCommands
 - Documented events and modules
 - Removed deprecated code.
 
Above mentioned points are the summary of the changes made to the source code.
This pull request makes considerable changes to the code structure and current code of the bot. This pull request may contain some bugs but I have tested all the commands and made respective error handlers in the code. feel free to mention any issues :)

## Check List (mark all applicable checkboxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots (if applicable)

 Original           | Updated
 :--------------------: |:--------------------:
 original screenshot | updated screenshot |

2021-12-29 16:28 UTC, DhansAL commented
omg this must be having a lot of typos (T_T) I'll try to make as less as possible @Panquesito7

2021-12-30 15:28 UTC, Panquesito7 requested changes
Hey there! I just merged #142. Can you please resolve the merge conflicts [**here**](https://github.com/commclassroom/classroom-monitor-bot/pull/146/conflicts)? Let us know if you need any help! 😃
Here's a very detailed guide on how to fix merge conflicts, from GitHub Docs: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github

2021-12-30 15:29 UTC, DhansAL commented
sure! will do this asap

2021-12-31 03:02 UTC, DhansAL commented
i have removed all the conflicts, you can review the code now ^_^

2022-01-02 11:27 UTC, DhansAL commented
Is anyone having any issues with this pull request? I'll be happy to help ^_^

2022-01-04 07:52 UTC, SiddhantKhisty approved these changes
Looks good to me

2022-01-07 21:28 UTC, Panquesito7 commented on package.json
> +
```suggestion
```

2022-01-07 21:33 UTC, Panquesito7 approved these changes
Let's give it a go! 🚀 Thanks so much for your contribution! 😄👍

2022-01-07 21:37 UTC, merged